# Generated by Django 3.2 on 2021-07-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
